/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTrackArgs } from "./CreateTrackArgs";
import { UpdateTrackArgs } from "./UpdateTrackArgs";
import { DeleteTrackArgs } from "./DeleteTrackArgs";
import { TrackCountArgs } from "./TrackCountArgs";
import { TrackFindManyArgs } from "./TrackFindManyArgs";
import { TrackFindUniqueArgs } from "./TrackFindUniqueArgs";
import { Track } from "./Track";
import { ArtistFindManyArgs } from "../../artist/base/ArtistFindManyArgs";
import { Artist } from "../../artist/base/Artist";
import { User } from "../../user/base/User";
import { TrackService } from "../track.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Track)
export class TrackResolverBase {
  constructor(
    protected readonly service: TrackService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "read",
    possession: "any",
  })
  async _tracksMeta(
    @graphql.Args() args: TrackCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Track])
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "read",
    possession: "any",
  })
  async tracks(@graphql.Args() args: TrackFindManyArgs): Promise<Track[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Track, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "read",
    possession: "own",
  })
  async track(
    @graphql.Args() args: TrackFindUniqueArgs
  ): Promise<Track | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Track)
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "create",
    possession: "any",
  })
  async createTrack(@graphql.Args() args: CreateTrackArgs): Promise<Track> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Track)
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "update",
    possession: "any",
  })
  async updateTrack(
    @graphql.Args() args: UpdateTrackArgs
  ): Promise<Track | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Track)
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "delete",
    possession: "any",
  })
  async deleteTrack(
    @graphql.Args() args: DeleteTrackArgs
  ): Promise<Track | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Artist], { name: "artists" })
  @nestAccessControl.UseRoles({
    resource: "Artist",
    action: "read",
    possession: "any",
  })
  async resolveFieldArtists(
    @graphql.Parent() parent: Track,
    @graphql.Args() args: ArtistFindManyArgs
  ): Promise<Artist[]> {
    const results = await this.service.findArtists(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldUser(
    @graphql.Parent() parent: Track
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
